asset_sync:
  FOG_DIRECTORY:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_REGION:
redis:
  host: localhost
  port: 6379
  db: 0
  namespace: woca
  password:
sidekiq:
  username:
  password:
smtp:
  user_name:
  password:
  authentication:
  address:
  port:
  domain:
global:
  SECRET_KEY_BASE:
db:
  database:
  hosts:
  options:
    user:
    password:
    auth_source:
    ssl:
razorpay:
  key:
  secret:
